language: node_js
node_js:
  - "8.10"
script:
  - npm install
  - ionic build browser
  - sudo npm i -g firebase-tools
  - sudo npm i -g firebase
  - echo "Realizando deploy aplicacao no firebase"
after_success:
  - firebase use --token $FIREBASE_TOKEN bitparking-tcc
  - firebase deploy --project bitparking-tcc --token $FIREBASE_TOKEN --debug
