language: node_js
node_js:
  - "8.10"
install:
  - npm install -g firebase-tools
  - npm install -g ionic cordova
script:
  - sudo rm -r node_modules
  - npm install
  - ionic cordova build browser
  - echo "Realizando deploy aplicacao no firebase"
after_success:
  - firebase use --token $FIREBASE_TOKEN bitparking-tcc
  - firebase deploy --project bitparking-tcc --token $FIREBASE_TOKEN